### ISSUE TITLE
多选组件有，es5版本的吗？

### ISSUE THREAD

**Issue by yyccQQu** [veedrin/qing#3]
大佬，多选组件有，es5版本的吗？因为项目不支持es6. 基本用的jquery。
![image](https://user-images.githubusercontent.com/32674176/54975352-669b8600-4fc9-11e9-8a97-c22833b63b4e.png)
还有这个布局怎么写啊，想不出来了，帮我解答一下，谢谢了

**Comment by veedrin** [comment]
没有 es5 版本的。你可以改造一下，把 class 改成 function 差不多了

首先有两列，这里的要求是用`fr`单位，然后它说总共六份，所以：
```css
#garden {
    grid-template-columns: 1fr 5fr;
}
```
